travis-ci/travis-migrations

Gemfile
Gemfile.lock
Rakefile

This ensures that when a new migration is created, the structure.sql is updated.

check that structure.sql is being updated when a new migration is added

---

db/migrate/20160107120927_add_cron_table.rb

new version of table for upcoming cron jobs, see travis-ci/travis-api#225

add table for cron jobs 

---

db/migrate/20160303165750_add_debug_options_to_jobs.rb

This column acts as a payload for debug build work

Add debug_otions column to jobs

---

Gemfile.lock
db/structure.sql

Update Gemfile.lock to latest bundler and updates structure.sql with latest migration to revert previous job states

Update Gemfile.lock and structure.sql with latest migration

---

.travis.yml
README.md
Rakefile
config/database.yml.travis
db/logs/migrate/20161116162355_create_logs.rb
db/logs/migrate/20161116162356_create_log_parts.rb
db/logs/migrate/logs_migration.rb
spec/travis_migrations_spec.rb

@igorwwwwwwwwwwwwwwwwwwww I tried a couple of things - I think your approach with the ENV var is the right way to go. I tried this and felt like it was a good way to accommodate having the same DB locally and different DBs remotely, but would like your feedback. I think we may want to push for using 2 DBs locally and in test to better reflect production, what do you think? If nothing else, I feel like the suggestion of having the LogsMigration class that ensures the logs migrations are run agains the correct connection is a good thing to add.

some suggestions

---

db/migrate/20161101000000_add_next_run_last_run_to_crons.rb
db/migrate/20161101000001_add_dont_run_if_recent_build_exists.rb
db/structure.sql

The corresponding PR that was testing with travis-api is https://github.com/travis-ci/travis-migrations/pull/19 which needn't be merged.

Add next_run, last_run and dont_run_if_recent_build_exists columns to crons

---

README.md
db/main/structure.sql

update readme - add RAILS_ENV info, remove export

---

db/main/migrate/20170316000000_queueable_jobs_create.rb
db/main/migrate/20170316000001_queueable_jobs_index_job_id.rb
db/main/structure.sql
spec/travis_migrations_spec.rb

For https://github.com/travis-pro/team-teal/issues/1247#issuecomment-287129484

Create queueable jobs

---

README.md

This update information in the readme regarding deployment of `travis-migrations` now that Slack deployment has been set up.
This addresses an issue causing this incident: https://github.com/travis-pro/incidents/issues/225

update readme with new deployment info

---

db/main/structure.sql

To go with https://github.com/travis-ci/travis-migrations/pull/49

Update SQL structure

---

db/main/migrate/20170405000000_tags_create.rb
db/main/migrate/20170405000001_requests_add_branch_id_and_tag_id.rb
db/main/migrate/20170405000002_commits_add_branch_id_and_tag_id.rb
db/main/migrate/20170405000003_builds_add_branch_id_and_tag_id.rb
db/main/structure.sql
spec/travis_migrations_spec.rb

This is for: https://github.com/travis-ci/travis-gatekeeper/pull/167

Create tags, add branch_id and tag_id to commits and branches

---

db/main/migrate/20170419093249_add_source_to_subscriptions.rb
db/main/structure.sql

https://github.com/travis-pro/team-teal/issues/1860

Adds source to subscriptions

---

db/main/migrate/20170620144500_add_indexes_on_builds_and_jobs_and_branches.rb
db/main/structure.sql

refs travis-pro/team-teal#2028
refs travis-pro/team-teal#2029
refs travis-pro/team-teal#2030

add indexes for builds, jobs, branches

---

db/main/migrate/20170831000000_create_trial_allowances.rb
db/main/structure.sql
spec/travis_migrations_spec.rb

See https://github.com/travis-pro/team-teal/issues/2123

WIP Add trial allowances table

---

db/main/migrate/20170911172800_add_index_on_jobs_updated_at.rb

this will allow for incremental imports into redshift.

add index on jobs updated_at

---

db/main/structure.sql

Change the strucure.sql

---

db/main/migrate/20180213000000_users_add_suspended_at.rb
db/main/structure.sql

this is needed for user management in enterprise

add suspended_at to users

---

db/main/migrate/20180305143800_index_builds_on_repository_id_where_state_not_finished.rb
db/main/structure.sql

add index for api Active::ForOwner endpoint

---

db/main/migrate/20180321102400_index_jobs_on_repository_id_where_state_running.rb
db/main/structure.sql

add index for scheduler running job count query

---

Gemfile.lock
db/main/migrate/20180410000000_requests_drop_payload.rb
db/main/structure.sql

🎉 
(also bumps loofah in order to get rid of the vulnerability warning)

Drop requests payload

---

db/main/migrate/20180417000000_index_builds_organizations_users_on_updated_at.rb
db/main/structure.sql

builds
users
repositories
organizations
This is to help with incremental data load for #analytics purposes.

Add index updated_at on 4 tables

---

db/main/migrate/20180425100000_add_removed_at_on_installations.rb
db/main/structure.sql

Add removed_at to installations table

---

db/main/migrate/20180531000000_create_request_yaml_configs.rb
db/main/structure.sql
spec/travis_migrations_spec.rb

We want to start storing the raw YAML as part of the upcoming UI changes for travis-yml.
https://github.com/orgs/travis-pro/projects/10

Add request yaml configs table

---

db/main/migrate/20180620000000_index_builds_on_repository_id_event_type_id.rb
db/main/structure.sql

refs https://github.com/travis-ci/reliability/issues/105

add index on builds for pull requests tab

---

db/main/migrate/20180725000000_create_cancellations.rb
db/main/structure.sql
spec/travis_migrations_spec.rb

Required by travis-pro/billing#230.
Note: `structure.sql` includes a couple of unrelated changes because it hadn't been updated in some previous pull request, apparently.

Add cancellations table

---

db/main/migrate/20180822000000_create_email_unsubscribes.rb
db/main/structure.sql
spec/travis_migrations_spec.rb

Fixes travis-pro/team-teal#2775

Add email_unsubscribes table

---

db/main/migrate/20180823000000_add_preferences.rb
db/main/structure.sql

Needed for upcoming work on build email settings.
https://github.com/travis-pro/team-teal/issues/2781

Add preferences column to users table

---

bin/migrate_down
bin/migrate_up
bin/perform_migrations

Sometimes I want to execute a few migrations one after another, this
commits add 2 scripts to help with that: bin/migrate_up and
bin/migrate_down

Add a few useful scripts

---

db/main/migrate/20190109000000_create_beta_migration_request_table.rb
db/main/migrate/20190118000000_add_beta_migration_request_column_to_organizations.rb
db/main/structure.sql
spec/travis_migrations_spec.rb

Part of https://github.com/travis-pro/team-teal/issues/2902

Add migration to create BetaMigrationRequest table

---

db/main/migrate/20190329093854_create_gatekeeper_workers.rb
db/main/structure.sql
spec/travis_migrations_spec.rb

This table is needed in order to give gatekeeper workers a range of ids that they can use to identify itself.

Add `gatekeeper_workers`

---

db/main/migrate/20190502175059_add_mergeable_state_to_pull_requests.rb
db/main/migrate/20190605155459_add_pull_request_mergeable_state_to_equests.rb
db/main/migrate/20190605155459_add_pull_request_mergeable_to_requests.rb
db/main/structure.sql

Required for travis-ci/product#181

Add columns for mergeable state

---

db/main/structure.sql

I forgot to add the updated structure.sql for #190. 
This adds the `migration_requests` table, which was also missing.

Add missing structure elements

---

db/main/migrate/20190801120510_add_more_deleted_tables.rb
db/main/sql/create_soft_delete_repo_data.sql
db/main/structure.sql
spec/travis_migrations_spec.rb

This commit adds request_raw_configs and request_raw_configurations to
the soft delete procedure.

Soft delete misses two additional tables

---

db/main/migrate/20190815152336_add_com_id_to_more_tables.rb
db/main/structure.sql

Initially I didn't think that com_ids are needed for these tables, but
it will make some optimisations a bit easier, so I'm adding them now.

Add com id to request_configs and request_yaml_configs

---

db/main/migrate/20200312184018_add_user_utm_params_table.rb
db/main/structure.sql
spec/travis_migrations_spec.rb

Required for this ticket:https://travisci.assembla.com/spaces/Web/tickets/283
Alternative implementation of https://github.com/travis-ci/travis-migrations/pull/217

Add user_utm_params table to store utm data

---

Gemfile.lock
db/main/migrate/20210614140633_add_server_type_to_repositories.rb
db/main/structure.sql

Bug fix cycle 10

---

Dockerfile

added apt update in the docker file

added apt update in docker file

---

.travis.yml

Update .travis.yml for build config

---

.travis.yml
Makefile
db/main/migrate/20220610092916_most_recent_job_ids_for_user_repositories_by_states_lw.rb
db/main/structure.sql

[TBT-84](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=84) Enterprise merge (PR: #291)

[TBT-84] Enterprise merge (#291)

---

db/main/migrate/20240823085523_add_vmsize_to_jobs.rb
db/main/structure.sql

[TBT-80](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=80) - vm_size in jobs and deleted_jobs tables (#296)

Release 2024 09 02

---

db/main/migrate/20250109121404_create_account_env_vars_table.rb
db/main/structure.sql
spec/travis_migrations_spec.rb

[TBT-137] Be able to use environment variables across different repo (#300)

Release 2025 03 19
