db/structure.sql

For the last two migrations added here, the `structure.sql` was not updated/committed. Therefore tests which rely on this migrations fail, see travis-ci/travis-api#225

update structure to include new migrations

---

db/migrate/201604121130200_builds_drop_index_owner_type.rb
db/migrate/201604121130700_repositories_drop_index_last_build_started_at.rb
db/migrate/20160412121405_jobs_drop_index_type.rb
db/migrate/20160412123900_jobs_drop_index_source_type.rb
db/structure.sql

This addresses this issue: https://github.com/travis-pro/team-teal/issues/778
It removes the following indexes:
`index_jobs_on_type`
`index_jobs_on_source_type`
`index_builds_on_owner_type`
`index_repositories_on_last_build_started_at`
It HAS NOT removed the `index_commits_on_repository_id` index as this is one that @henrikhodne uses occasionally when debugging.

remove unused indexes

---

db/migrate/20160422104300_builds_add_index_number.rb
db/structure.sql

This adds an index for `number` on the builds table.
It should help API queries that include `after_number` in the params, eg `.../builds?after_number=1500`.

add index builds on number

---

db/migrate/20160623133900_create_previous_job_states.rb
db/migrate/20160623133901_add_previous_states_triggers.rb
db/structure.sql

I need to have a list of previous states of each job to write a tool for
displaying builds execution history (currently this information is lost
whenever the job is restarted). Ideally I would save this information in
a JSONB column, but we're on postgresql 9.3, so neither JSONB nor
functions to modify it are available.

Add previous_job_states table and triggers to fill it

---

.travis.yml
README.md
config/database.yml
db/migrate/20120702111126_create_subscriptions.rb
db/migrate/20120703114226_add_billing_email_credit_card_data_to_subscriptions.rb
db/migrate/201207261749_create_plans.rb
db/migrate/20120731074000_add_amount_to_plans.rb
db/migrate/20120803164000_create_invoices.rb
db/migrate/20120803182300_add_invoice_id_to_invoices.rb
db/migrate/20120804122700_add_stripe_invoice_id_to_invoices.rb
db/migrate/20120806120400_add_plan_to_subscriptions.rb
db/migrate/20120820164000_rename_plan_on_subscriptions.rb
db/migrate/20120905093300_create_stripe_events.rb
db/migrate/20120905171300_add_event_id_to_stripe_events.rb
db/migrate/20120913143800_add_subscriptions_coupon.rb
db/migrate/20130306154311_create_pgcrypto_extension.rb
db/migrate/20130618084205_add_coupons.rb
db/migrate/20130701175200_add_contact_id_to_subscriptions.rb
db/migrate/20150609175200_add_cancelation_columns_to_subscriptions.rb
db/migrate/20150615103059_add_status_to_subscriptions.rb
db/structure.sql
lib/travis/migrations/version.rb
spec/travis_migrations_spec.rb

This adds all the pro-migrations to this repo, so that we only now add migrations to the one repo.
A change has been made to the `config/database.yml` whereby it now fetches a `DATABASE_NAME` ENV variable in order to know what *local* database to run migrations on (or uses a default as defined). This ENV variable can be overridden manually when running migrations via the command line. Details of how to do this have been added to the README.
The spec has also been updated to include the new tables.
Migrations have been tested locally, on travis-ci, and also tested on the `travis-staging` db. The migration ran successfully, adding the following (previously pro) tables.

Add pro-migrations files into migrations

---

db/migrate/20161908103700_add_avatar_url_to_users.rb
db/structure.sql

This adds an avatar_url column to the users table so that we can use a users avatar_url if they have one.
The migration has been run on staging successfully.
https://github.com/travis-pro/team-teal/issues/1288

add avatar_url column to users table

---

db/migrate/20161028154600_remove_type_indices.rb
db/structure.sql

This migration removes `index_jobs_on_owner_type` and `index_requests_on_event_type`.
Heroku doesn't use these indexes. 
The migrations have been deployed to both .org and .com staging DBs. There don't seem to be any issues on travis-ci staging, nor in admin staging apps...

Remove unused `type` indexes

---

db/main/migrate/20161221171300_builds_add_index_repository_id_and_number.rb
db/main/structure.sql

this adds an index to address a problem with build histories taking a long time to load when a repo has many thousands of builds.
I've run it locally and it adds the exact same index that was created on the .com production DB to test with:
`"index_builds_on_repository_id_and_number" btree (repository_id, (number::integer))`

add builds index repository id and number

---

db/main/migrate/20170609174400_drop_unused_indexes_on_jobs_and_builds.rb

these indexes have already been dropped on production, `schema_migrations` inserts are still missing though.

drop unused indexes on jobs and builds

---

.travis.yml
README.md

Our staging DBs have been upgraded to postgresql 9.6 and our production DBs will be upgraded soon. 
However, Enterprise won't be updated for a while so we need to ensure migrations will be backwards compatible with the version it uses, 9.3.
This PR adds a matrix that runs two separate jobs, one using postgres 9.3, one using postgres 9.6 thus ensuring any migrations will be compatible with both.

Add matrix to run specs on Postgres versions 9.3 and 9.6

---

db/main/migrate/20171025000000_add_updated_at_trigger_to_builds_and_jobs.rb
db/main/structure.sql
spec/set_updated_at_trigger_spec.rb
spec/travis_migrations_spec.rb

This PR adds triggers on builds and jobs tables that set `updated_at`
field to `now()` on `INSERT` and on `UPDATE`, with an exception of not
setting the column when a row hasn't been changed.

Add set_updated_at triggers to jobs and builds

---

db/main/migrate/20171211000000_add_repository_id_branch_event_type_index_on_builds.rb

Drops the average for our current most expensive query from 800ms to 0ms. 👍

new conditional index: index_builds_on_repository_id_and_branch_and_event_type

---

db/main/migrate/20180130000000_add_repositories_owner_id_owner_type_index.rb

This is needed for queries where we need to get only repositories where
we want only a specific owner_type.
I need it specifically for https://github.com/travis-ci/travis-api/pull/631

Add index on repositories(owner_id, owner_type)

---

README.md
db/main/migrate/20180420000000_constraints_and_indexes_for_gh_apps.rb
db/main/structure.sql

Don't know if the changes to structure.sql are an issue here – I ran the migrations against PostgreSQL 9.6.1.
These are both for performance when querying and also to avoid sync creating duplicate records that will be hard to work around later.

Unique installations by github id, index repos

---

db/main/migrate/20180429000000_index_repositories_on_owner_name_and_name.rb
db/main/structure.sql

this is currently the top query at about 15% of all runtime:
SELECT "id" FROM "repositories" WHERE (("invalidated_at" IS NULL) AND ("owner_name" = ?) AND ("name" = ?))
it is coming from sync, and it is missing a good index it can use.
thus it needs to do a bitmap index scan on:
* `index_repositories_on_name`
* `index_repositories_on_owner_name`
thus potentially having to scan a lot of repos or owners for
common names. it also needs to reference both of those indexes
and still do a filter for invalidated_at in the end.
with this new index it can index scan directly!
results:
(drop on the right)

add new index on repositories (owner_name, name)

---

db/main/migrate/20180501000000_index_jobs_on_owner_where_state_running.rb
db/main/structure.sql

this is for two common scheduler queries that were scanning a lot of records and loading 50 megs per call.
this is the query: https://app.pganalyze.com/databases/15694/queries/824910735
old query plan: https://explain.depesz.com/s/Y0Q
new query plan: https://explain.depesz.com/s/iFJh
results:

add an index on jobs (owner_id, owner_type) where state in ('queued', 'received', 'started')

---

.gitignore
Dockerfile
script/dump-schema-docker.sh

This is still resulting in differences in the stucture.sql file, which is making me question the whole purpose of this PR, but anyway.
```
root@b8848c6d9c47:/travis-migrations# pg_dump --version
pg_dump (PostgreSQL) 9.6.9
```

Run migrations inside container

---

db/main/migrate/20180410000000_requests_drop_payload.rb
db/main/migrate/20180614000000_drop_requests_config.rb
db/main/migrate/20180614000001_drop_builds_config.rb
db/main/migrate/20180614000002_drop_jobs_config.rb

The decision how to deal with backfilling tasks on Enterprise has yet to be made, but this would be a minimal, conservative approach to move this forward.

Drop [requests|builds|jobs].config unless on enterprise

---

db/main/migrate/20180829000000_make_email_unsubscribes_id_bigint.rb
db/main/structure.sql

As suggested by @igorwwwwwwwwwwwwwwwwwwww in https://github.com/travis-ci/travis-migrations/pull/137#issuecomment-415439315.
Since `users` and `repositories` have regular ints as ids, I left the foreign keys unchanged, any suggestion to do otherwise?
The table is basically empty at this point (just some rows created while testing the feature) so I assume the migration can be run without special care but I'm happy to be corrected about this.

Change email_unsubscribes.id to bigint

---

db/main/migrate/20180906000000_add_index_users_preferences_build_emails.rb
db/main/structure.sql

In order to prevent the potential performance problem introduced in https://github.com/travis-ci/travis-hub/pull/171, as suggested by @igorwwwwwwwwwwwwwwwwwwww.
The query plan now looks like this:
```
EXPLAIN for: SELECT "emails".* FROM "emails" INNER JOIN "users" ON "users"."id" = "emails"."user_id" WHERE "emails"."email" = 'me@email.com' AND (preferences->>'build_emails' = 'false')
QUERY PLAN
------------------------------------------------------------------------------------------------------------
Nested Loop  (cost=4.31..20.86 rows=1 width=56)
Join Filter: (emails.user_id = users.id)
->  Index Only Scan using user_preferences_build_emails_false on users  (cost=0.12..8.14 rows=1 width=4)
->  Bitmap Heap Scan on emails  (cost=4.19..12.66 rows=5 width=56)
Recheck Cond: ((email)::text = …
```

Add index on build_emails user preference

---

db/main/migrate/20181116800000_add_constraints_to_multiple_tables.rb
db/main/structure.sql
spec/repo_counts_spec.rb

We lack foreign key constraints on most of the foreign keys in the DB. This PR fixes the situation. It doesn't go through all of the foreign keys, but deals with most important associations. I will go through the rest of the keys at a later time, but for now I wanted to focus on stuff that's most important during the migration of data from .org to .com.

Add foreign key constraints to multiple tables

---

db/main/migrate/20181203075819_add_set_unique_name_trigger_to_branches.rb
db/main/migrate/20181203080356_create_index_on_branches_unique_name_and_repository_id.rb
db/main/sql/triggers/create_set_unique_name.sql
db/main/sql/triggers/drop_set_unique_name.sql
db/main/structure.sql
spec/set_unique_name_spec.rb

We have a problem with the code in gatekeeper and possibly API
introducing duplicated branches. We want to add an index on
`(repository_id, name)`, but we need to clean the table first and in
order to do that we need to fix the bug, so no new duplicates are
introduced during index creation. Otherwise we would have to use a
maintenance window for index creation and stop all the apps from
processing, which would be much harder operationally and add a
considerable delay.
In this commit I introduce a simple way to overcome the problem. A new
column `unique_name` is added to branches. The column is set on UPDATEs
and INSERTs to the branches table with a value of the `name` column. An
index is also added on `(repository_id, unique_name) WHERE unique_name
IS NOT NULL`, which enforces an index on …

Make branches unique without cleaning up the table

---

db/main/migrate/20181205152712_add_unique_index_to_crons_on_branch_id.rb

There is currently an index on `branch_id`, but it's not unique. Ecto
requires this in order to deal with conflicts on upserts. Also, this is
my understanding of what our current business logic is; there are
currently no duplicate branches, which seems to confirm that this is the
desired behavior.

Add unique index to crons on branch_id

---

db/main/migrate/20190204000000_make_subscription_owner_not_nullable.rb
db/main/structure.sql

Note: this migration will FAIL if run because there are currently rows where
this field is NULL (and this is the point of this change). Adding a default
makes no sense in this case, so those rows need to be dealt with before
deploying this change.

Make subscription owner fields not nullable

---

db/main/migrate/20190410121039_make_set_unique_number_trigger_run_only_on_insert.rb
db/main/structure.sql

If the set_unique_number procedure runs on UPDATE on the builds table we
could run into problems when trying to update builds that have
duplicated number. That's why we should run it only on INSERT. It's
still fine for consistency because we generally don't modify build
numbers.

Run set_unique_number only on INSERT

---

db/main/sql/delete_cascade.sql

I created a procedure in order to make it easier to remove a repository and all its data (because it needs referenced rows to be deleted as well). It's already deployed to production as it was needed for support but I totally forgot to add it to the main branch.

Procedure to delete a repository and all its dependencies

---

db/main/migrate/20190417072423_alter_builds_unique_number_index.rb
db/main/migrate/20190417072838_reinstall_set_unique_number_trigger.rb
db/main/sql/triggers/create_set_unique_number.sql
db/main/structure.sql
spec/set_unique_number_spec.rb

Initially I wanted to not update unique_number when performing an UPDATE
to make things simple but after giving it more thought I decided that
it's better to be able to do it on both UPDATE and INSERT. Normally we
don't update builds.number but it might still be valuable to have the
consistency when doing some kind of meintenance (like renumbering
builds).

Allow to skip setting unique_number

---

db/main/migrate/20190510121000_add_repos_index_on_lower_owner_name_and_name.rb
db/main/structure.sql

This new index is needed to accommodate changes in api regarding lowercasing owner and repo names
(see https://github.com/travis-ci/travis-api/pull/909)
The migrations have been deployed to staging and run successfully there.

add repos index on lower owner name and name

---

README.md
Rakefile

With `rake gen_migration["foo"]`, we generate the migration file
with the name `foo` and the timestamp we need.
This reduces the work needed to created a new migration.

Add gen_migration rake task

---

db/main/migrate/20200214144655_add_index_to_job_versions_on_job_id.rb

We have a slowish query currently when querying `job_versions` (appears to be executed whenever we restart a job):
```sql
SELECT MAX("job_versions"."number")
FROM "job_versions"
WHERE "job_versions"."job_id" = $1
```
I created 100k rows locally and ran the query, average execution time: 15-24ms.
I then added this index. Average query execution time: 0.3-0.5ms.

Add index to job_versions on job_id

---

db/main/migrate/20202427123653_add_column_has_local_registration_to_table_subscriptions.rb

The new column is required by the accounts department.
> We need to have a mandatory question: “Is your company registered locally for VAT/GST”
> If reply is “Yes” – customer needs to complete mandatory field “Tax ID”
> If “No” – customer proceeds with order
> 
> **We will need to be able to extract a report where customer answered “No”, as this will mean customer B2C and we need to track the threshold manually

added the new column to support the internation vat ids

---

db/main/structure.sql

adding the newly created field manually because the PostgreSQL is different on local development environment

update the structure

---

.travis.yml

This PR removes snap because It was added in the past to support outdated docker and for reason it was causing issues with Quay.

Remove snap

---

script/upload_structure.rb

*Note:
Because Aws::S3::Client requires the region parameter AWS_REGION env is set to `us-west-1` on this branch. I suppose it needs to be set on main when deployed to prod.

[Tbt-309] s3 export
